# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

addons:
    hosts:
        - kreta.test

language: php

php:
#    - 5.5
#    - 5.6
#    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - phpenv config-rm xdebug.ini

    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || mkdir -p /home/travis/go/{src,bin,pkg}'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || export GOPATH="/home/travis/go"'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || export PATH="$GOPATH/bin:$PATH"'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || go get github.com/Naktibalda/hhvm-serve'

#    - nvm install 4.2.1
#    - nvm use 4.2.1
    - composer self-update
    - composer update --no-interaction ${COMPOSER_OPTIONS}
#    - cd src/Kreta/Bundle/WebBundle
#    - npm install
#    - cd -

before_script:
    - cd tests/functional/fixtures

    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:create --env=test
    - bin/console cache:warmup --env=test

#    - bin/console assets:install --relative
#
#    - cd -
#    - cd src/Kreta/Bundle/WebBundle
#    - npm run dev

    - cd -
    - cp tests/behat.yml.dist behat.yml && cp tests/phpspec.yml.dist phpspec.yml

#### create config file for HHVM ####
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "pid = /tmp/hhvm.pid" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.server.port = 9000" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.server.type = fastcgi" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.server.default_document = index.php" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.log.use_log_file = true" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.log.file = /tmp/hhvm-error.log" >>/tmp/hhvm.ini'
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || echo "hhvm.repo.central.path = /tmp/hhvm.hhbc" >>/tmp/hhvm.ini'
#### start HHVM ####
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || hhvm --config "/tmp/hhvm.ini" --mode daemon'
#    - sleep 5

#### starting PHP built-in server ####
#    - '[[ "$TRAVIS_PHP_VERSION" == "hhvm" ]] || tests/functional/fixtures/bin/console server:start kreta.test:8000 --router=tests/functional/fixtures/web/app.php  >/dev/null 2>&1 &'
#### use berbeley's FastCGI-Serve instead of PHP built-in server ####
    - '[[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] || hhvm-serve --document-root=tests/functional/fixtures/web --listen=kreta.test:8000 >/dev/null 2>&1 &'


    - sleep 5

script:
#    - cd src/Kreta/Bundle/WebBundle
#    - node_modules/.bin/jest --verbose --coverage
#    - cd -

#    - vendor/bin/phpspec run

#    - vendor/bin/behat --stop-on-failure --suite=oauth
#    - vendor/bin/behat --stop-on-failure --suite=authentication
    - vendor/bin/behat --stop-on-failure --suite=user
    - vendor/bin/behat --stop-on-failure --suite=invitation
#    - vendor/bin/behat --stop-on-failure --suite=profile
#    - vendor/bin/behat --stop-on-failure --suite=issue
#    - vendor/bin/behat --stop-on-failure --suite=label
#    - vendor/bin/behat --stop-on-failure --suite=participant
#    - vendor/bin/behat --stop-on-failure --suite=issuePriority
#    - vendor/bin/behat --stop-on-failure --suite=project
#    - vendor/bin/behat --stop-on-failure --suite=status
#    - vendor/bin/behat --stop-on-failure --suite=statusTransition
#    - vendor/bin/behat --stop-on-failure --suite=workflow

#after_script:
#    - vendor/bin/coveralls -v
#
cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
    allow_failures:
#        - php: 7.0
#        - php: hhvm
